### ISSUE TITLE
Se debe refactorizar el código de producción para eliminar repeticiones

### ISSUE THREAD

**Issue by evolentini** [javelasco/CESE-TSSE#2]
En esta línea se debería llamar a la función `LedsAllTurnOff()` en lugar de repetir la asignación de valores a la variable.

https://github.com/javelasco/CESE-TSSE/blob/b4c2226195cded0cde52ef88a2ab6655df2794d1/Leds/src/Leds.c#L16

Ademas hay código repetido en el control de limites del led, eso se podría resolver agregando un macro  que efectue el control de limites en esa función.

**Comment by javelasco** [comment]
Corregido.
