### ISSUE TITLE
Se puede simplificar el código de producción

### ISSUE THREAD

**Issue by evolentini** [javelasco/CESE-TSSE#3]
Este bloque de código 

https://github.com/javelasco/CESE-TSSE/blob/b4c2226195cded0cde52ef88a2ab6655df2794d1/Leds/src/Leds.c#L46-L51

se puede simplificar como

```c
       return ((*puerto) & LED_TO_MASK(led)) != 0);
```

**Comment by javelasco** [comment]
Corregido.
