### ISSUE TITLE
No se debe utilizar la directiva `#include` con un archivo tipo `.c`

### ISSUE THREAD

**Issue by evolentini** [javelasco/CESE-TSSE#6]
Si bien es posible y funciona no es correcto utilizar la directiva `#include` con archivos `.c` que tienen código fuente sino solamente con archivos `.h` que tienen declaraciones. Los archivos de código fuente deben ser complicados por separado y enlazados en lugar de incluidos en otro archivo de código fuente.

**Comment by javelasco** [comment]
Corregido.

**Comment by evolentini** [comment]
Este error no fue completamente corregido:

https://github.com/javelasco/CESE-TSSE/blob/f76e0d89495c714c046dd0017477335aaf78c1f5/TP4_Testing_Unitario/src/DHT.c#L2

y el planteo general del todo el TP4 es incorrecto, como se explicó en el issue #5, por lo que la nota del TP4 queda sin cambios.
